### ISSUE TITLE
'Recursion limit' in certain recipe combinations

### ISSUE THREAD

**Issue by natri0** [JohnTheCoolingFan/factorio-web-calculator#1] opened 2022-05-06 16:07 UTC
Just found out that if you try to calculate `low-density-structure` and `satellite` with items/s set to `1` at the same time, a message about a recursion limit shows up.

![Screenshot](https://i.imgur.com/dvZlewk.png)

[Console logs captured in Firefox (warning: 10k lines long)](https://gist.githubusercontent.com/nullium21/352454c46ced46d12a38d2feec71e388/raw/f3a3a839acb3a74bf037cf7e812dd4e195cacbe5/log.txt)

**Comment by JohnTheCoolingFan** [comment] 2022-05-12 06:19
Seems to be fixed *somehow* on the latest commit

**Comment by JohnTheCoolingFan** [comment] 2022-05-17 12:12
Can't reproduce on 0.2.0, closing

**Closed as completed by JohnTheCoolingFan** 2022-05-17 12:12 UTC
Labels: bug
